name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure script is executable
        run: chmod +x uninstallr.sh

      - name: Install ShellCheck
        run: brew update && brew install shellcheck

      - name: Lint with ShellCheck
        run: shellcheck -x uninstallr.sh

      - name: Dry-run test (Spotify)
        run: |
          set -o pipefail
          ./uninstallr.sh --dry-run "Spotify" || true


